[package]
name = "Rust_Iced_Solitaire"
version = "0.1.0"
authors = ["Charles Ray<icedpygui@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { version = "0.13.1", features = ["advanced", "canvas", "debug", "image"] }
rand = "0.8.3"
